// ============================================================
// HKSchoolPlace — Generated by `npm run supabase:types`
// DO NOT EDIT MANUALLY.
// ============================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      activities: {
        Row: {
          address: string | null
          age_max: number | null
          age_min: number | null
          category: string
          contact_phone: string | null
          contact_url: string | null
          created_at: string
          description: string | null
          district: string | null
          end_date: string | null
          fee: number | null
          fee_note: string | null
          id: string
          image_url: string | null
          is_active: boolean
          match_confidence: string | null
          organizer: string | null
          raw_extracted: Json | null
          schedule: string | null
          source: string
          source_url: string | null
          start_date: string | null
          title: string
          updated_at: string
        }
        Insert: {
          address?: string | null
          age_max?: number | null
          age_min?: number | null
          category: string
          contact_phone?: string | null
          contact_url?: string | null
          created_at?: string
          description?: string | null
          district?: string | null
          end_date?: string | null
          fee?: number | null
          fee_note?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          match_confidence?: string | null
          organizer?: string | null
          raw_extracted?: Json | null
          schedule?: string | null
          source: string
          source_url?: string | null
          start_date?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          address?: string | null
          age_max?: number | null
          age_min?: number | null
          category?: string
          contact_phone?: string | null
          contact_url?: string | null
          created_at?: string
          description?: string | null
          district?: string | null
          end_date?: string | null
          fee?: number | null
          fee_note?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          match_confidence?: string | null
          organizer?: string | null
          raw_extracted?: Json | null
          schedule?: string | null
          source?: string
          source_url?: string | null
          start_date?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      admission_intel: {
        Row: {
          academic_year: string
          application_result: string
          created_at: string
          fee_interview_hkd: number | null
          fee_registration_hkd: number | null
          grade_applied: string
          has_second_interview: boolean | null
          helpful_count: number
          id: string
          interview_language: string | null
          interview_type: string
          notes: string | null
          offer_month: string | null
          queue_time: string | null
          rejection_reason: string | null
          school_id: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          academic_year: string
          application_result: string
          created_at?: string
          fee_interview_hkd?: number | null
          fee_registration_hkd?: number | null
          grade_applied: string
          has_second_interview?: boolean | null
          helpful_count?: number
          id?: string
          interview_language?: string | null
          interview_type: string
          notes?: string | null
          offer_month?: string | null
          queue_time?: string | null
          rejection_reason?: string | null
          school_id: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          academic_year?: string
          application_result?: string
          created_at?: string
          fee_interview_hkd?: number | null
          fee_registration_hkd?: number | null
          grade_applied?: string
          has_second_interview?: boolean | null
          helpful_count?: number
          id?: string
          interview_language?: string | null
          interview_type?: string
          notes?: string | null
          offer_month?: string | null
          queue_time?: string | null
          rejection_reason?: string | null
          school_id?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admission_intel_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admission_intel_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      app_feature_flags: {
        Row: {
          description: string | null
          enabled: boolean
          flag_key: string
          updated_at: string
        }
        Insert: {
          description?: string | null
          enabled?: boolean
          flag_key: string
          updated_at?: string
        }
        Update: {
          description?: string | null
          enabled?: boolean
          flag_key?: string
          updated_at?: string
        }
        Relationships: []
      }
      cron_run_logs: {
        Row: {
          completed_at: string | null
          error_message: string | null
          failed_count: number
          id: string
          job_name: string
          metadata: Json
          processed_count: number
          reminders_created: number
          sent_count: number
          started_at: string
          status: string
          status_updated: number
        }
        Insert: {
          completed_at?: string | null
          error_message?: string | null
          failed_count?: number
          id?: string
          job_name: string
          metadata?: Json
          processed_count?: number
          reminders_created?: number
          sent_count?: number
          started_at?: string
          status: string
          status_updated?: number
        }
        Update: {
          completed_at?: string | null
          error_message?: string | null
          failed_count?: number
          id?: string
          job_name?: string
          metadata?: Json
          processed_count?: number
          reminders_created?: number
          sent_count?: number
          started_at?: string
          status?: string
          status_updated?: number
        }
        Relationships: []
      }
      favorites: {
        Row: {
          created_at: string
          id: string
          reminder_days_before: number[]
          reminder_enabled: boolean
          school_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          reminder_days_before?: number[]
          reminder_enabled?: boolean
          school_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          reminder_days_before?: number[]
          reminder_enabled?: boolean
          school_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      intel_helpful_votes: {
        Row: {
          created_at: string
          id: string
          intel_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          intel_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          intel_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "intel_helpful_votes_intel_id_fkey"
            columns: ["intel_id"]
            isOneToOne: false
            referencedRelation: "admission_intel"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "intel_helpful_votes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      lcsd_programme_status: {
        Row: {
          enrolment_status: string | null
          is_full: boolean | null
          last_checked_at: string | null
          programme_id: string
          seats_available: number | null
        }
        Insert: {
          enrolment_status?: string | null
          is_full?: boolean | null
          last_checked_at?: string | null
          programme_id: string
          seats_available?: number | null
        }
        Update: {
          enrolment_status?: string | null
          is_full?: boolean | null
          last_checked_at?: string | null
          programme_id?: string
          seats_available?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "lcsd_programme_status_programme_id_fkey"
            columns: ["programme_id"]
            isOneToOne: true
            referencedRelation: "lcsd_programmes"
            referencedColumns: ["id"]
          },
        ]
      }
      lcsd_programmes: {
        Row: {
          age_max: number | null
          age_min: number | null
          category: string | null
          created_at: string | null
          district: string | null
          end_date: string | null
          enrolment_close_at: string | null
          enrolment_open_at: string | null
          fee_hkd: number | null
          id: string
          is_active: boolean | null
          last_scraped_at: string | null
          lcsd_programme_id: string
          name_en: string | null
          name_zh: string | null
          raw_url: string | null
          sessions_count: number | null
          start_date: string | null
          venue: string | null
        }
        Insert: {
          age_max?: number | null
          age_min?: number | null
          category?: string | null
          created_at?: string | null
          district?: string | null
          end_date?: string | null
          enrolment_close_at?: string | null
          enrolment_open_at?: string | null
          fee_hkd?: number | null
          id?: string
          is_active?: boolean | null
          last_scraped_at?: string | null
          lcsd_programme_id: string
          name_en?: string | null
          name_zh?: string | null
          raw_url?: string | null
          sessions_count?: number | null
          start_date?: string | null
          venue?: string | null
        }
        Update: {
          age_max?: number | null
          age_min?: number | null
          category?: string | null
          created_at?: string | null
          district?: string | null
          end_date?: string | null
          enrolment_close_at?: string | null
          enrolment_open_at?: string | null
          fee_hkd?: number | null
          id?: string
          is_active?: boolean | null
          last_scraped_at?: string | null
          lcsd_programme_id?: string
          name_en?: string | null
          name_zh?: string | null
          raw_url?: string | null
          sessions_count?: number | null
          start_date?: string | null
          venue?: string | null
        }
        Relationships: []
      }
      media_articles: {
        Row: {
          body_excerpt: string | null
          category: string | null
          content_type: string
          external_id: string
          fetched_at: string
          id: string
          published_at: string | null
          raw_metadata: Json
          school_match_status: string
          school_matches: Json
          source: string
          summary: string | null
          title: string
          updated_at: string
          url: string
        }
        Insert: {
          body_excerpt?: string | null
          category?: string | null
          content_type: string
          external_id: string
          fetched_at?: string
          id?: string
          published_at?: string | null
          raw_metadata?: Json
          school_match_status: string
          school_matches?: Json
          source: string
          summary?: string | null
          title: string
          updated_at?: string
          url: string
        }
        Update: {
          body_excerpt?: string | null
          category?: string | null
          content_type?: string
          external_id?: string
          fetched_at?: string
          id?: string
          published_at?: string | null
          raw_metadata?: Json
          school_match_status?: string
          school_matches?: Json
          source?: string
          summary?: string | null
          title?: string
          updated_at?: string
          url?: string
        }
        Relationships: []
      }
      programme_reminders: {
        Row: {
          created_at: string | null
          id: string
          reminder_type: string
          retry_count: number | null
          scheduled_at: string
          sent_at: string | null
          status: string | null
          subscription_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          reminder_type: string
          retry_count?: number | null
          scheduled_at: string
          sent_at?: string | null
          status?: string | null
          subscription_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          reminder_type?: string
          retry_count?: number | null
          scheduled_at?: string
          sent_at?: string | null
          status?: string | null
          subscription_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "programme_reminders_subscription_id_fkey"
            columns: ["subscription_id"]
            isOneToOne: false
            referencedRelation: "programme_subscriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      programme_subscriptions: {
        Row: {
          created_at: string | null
          id: string
          is_active: boolean | null
          notify_before_open_minutes: number | null
          programme_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          notify_before_open_minutes?: number | null
          programme_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          notify_before_open_minutes?: number | null
          programme_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "programme_subscriptions_programme_id_fkey"
            columns: ["programme_id"]
            isOneToOne: false
            referencedRelation: "lcsd_programmes"
            referencedColumns: ["id"]
          },
        ]
      }
      reminders: {
        Row: {
          created_at: string
          favorite_id: string
          id: string
          reminder_status: string
          reminder_type: string
          retry_count: number
          scheduled_date: string
          school_id: string
          sent_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          favorite_id: string
          id?: string
          reminder_status?: string
          reminder_type: string
          retry_count?: number
          scheduled_date: string
          school_id: string
          sent_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          favorite_id?: string
          id?: string
          reminder_status?: string
          reminder_type?: string
          retry_count?: number
          scheduled_date?: string
          school_id?: string
          sent_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reminders_favorite_id_fkey"
            columns: ["favorite_id"]
            isOneToOne: false
            referencedRelation: "favorites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reminders_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reminders_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      school_aliases: {
        Row: {
          alias: string
          alias_type: string
          confidence: number
          created_at: string
          id: string
          school_id: string
          source: string
        }
        Insert: {
          alias: string
          alias_type: string
          confidence?: number
          created_at?: string
          id?: string
          school_id: string
          source?: string
        }
        Update: {
          alias?: string
          alias_type?: string
          confidence?: number
          created_at?: string
          id?: string
          school_id?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "school_aliases_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      school_enrichments: {
        Row: {
          admission_hours: string | null
          application_process: string | null
          application_url: string | null
          cons_tags: Json | null
          content_hash: string | null
          interview_style: string | null
          last_crawled_at: string
          last_updated_at: string
          official_website: string | null
          open_day_date: string | null
          open_day_details: string | null
          pages_fetched: number | null
          pros_tags: Json | null
          quote_highlights: Json | null
          raw_extracted: Json | null
          reputation_last_updated: string | null
          reputation_summary: string | null
          school_id: string
          scrape_confidence: string | null
          scrape_notes: string | null
          scrape_status: string | null
          sentiment_positive_ratio: number | null
          source_count_by_platform: Json | null
          vacancy_k1: string | null
          vacancy_k2: string | null
          vacancy_k3: string | null
          vacancy_last_checked: string | null
        }
        Insert: {
          admission_hours?: string | null
          application_process?: string | null
          application_url?: string | null
          cons_tags?: Json | null
          content_hash?: string | null
          interview_style?: string | null
          last_crawled_at?: string
          last_updated_at?: string
          official_website?: string | null
          open_day_date?: string | null
          open_day_details?: string | null
          pages_fetched?: number | null
          pros_tags?: Json | null
          quote_highlights?: Json | null
          raw_extracted?: Json | null
          reputation_last_updated?: string | null
          reputation_summary?: string | null
          school_id: string
          scrape_confidence?: string | null
          scrape_notes?: string | null
          scrape_status?: string | null
          sentiment_positive_ratio?: number | null
          source_count_by_platform?: Json | null
          vacancy_k1?: string | null
          vacancy_k2?: string | null
          vacancy_k3?: string | null
          vacancy_last_checked?: string | null
        }
        Update: {
          admission_hours?: string | null
          application_process?: string | null
          application_url?: string | null
          cons_tags?: Json | null
          content_hash?: string | null
          interview_style?: string | null
          last_crawled_at?: string
          last_updated_at?: string
          official_website?: string | null
          open_day_date?: string | null
          open_day_details?: string | null
          pages_fetched?: number | null
          pros_tags?: Json | null
          quote_highlights?: Json | null
          raw_extracted?: Json | null
          reputation_last_updated?: string | null
          reputation_summary?: string | null
          school_id?: string
          scrape_confidence?: string | null
          scrape_notes?: string | null
          scrape_status?: string | null
          sentiment_positive_ratio?: number | null
          source_count_by_platform?: Json | null
          vacancy_k1?: string | null
          vacancy_k2?: string | null
          vacancy_k3?: string | null
          vacancy_last_checked?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "school_enrichments_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: true
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      schools: {
        Row: {
          address_en: string | null
          address_tc: string | null
          application_details: string | null
          application_fee_hkd: number | null
          application_status: string | null
          application_url: string | null
          created_at: string
          data_source: string
          district: string
          email: string | null
          fax: string | null
          fee_annual_hkd: number | null
          fee_certificate_updated_at: string | null
          fee_certificate_url: string | null
          fee_monthly_hkd: number | null
          fee_notes: string | null
          grades_offered: string[]
          has_nursery: boolean
          id: string
          inspection_report_updated_at: string | null
          inspection_report_url: string | null
          is_active: boolean
          kep_participant: boolean
          language_primary: string | null
          language_secondary: string | null
          last_profile_scraped_at: string | null
          last_verified_at: string | null
          latitude: number | null
          logo_url: string | null
          longitude: number | null
          master_data_notes: string | null
          name_en: string | null
          name_tc: string
          official_notice_updated_at: string | null
          official_notice_url: string | null
          official_profile_url: string | null
          open_day_details: string | null
          open_day_url: string | null
          other_fees_note: string | null
          phone: string | null
          registration_fee_hkd: number | null
          school_code: string | null
          school_type: string
          schooland_facilities_summary: string | null
          schooland_founded_year: number | null
          schooland_free_scheme: boolean | null
          schooland_group_tag: string | null
          schooland_intro: string | null
          schooland_nursery_service: string | null
          schooland_operator_name: string | null
          schooland_secondary_flags: Json
          schooland_session_label: string | null
          schooland_size_label: string | null
          schooland_source_fields: Json
          schooland_source_updated_at: string | null
          schooland_source_url: string | null
          schooland_staff_count: number | null
          schooland_teacher_student_ratio: string | null
          schooland_teaching_summary: string | null
          schooland_url: string | null
          session_type: string | null
          updated_at: string
          website: string | null
        }
        Insert: {
          address_en?: string | null
          address_tc?: string | null
          application_details?: string | null
          application_fee_hkd?: number | null
          application_status?: string | null
          application_url?: string | null
          created_at?: string
          data_source: string
          district: string
          email?: string | null
          fax?: string | null
          fee_annual_hkd?: number | null
          fee_certificate_updated_at?: string | null
          fee_certificate_url?: string | null
          fee_monthly_hkd?: number | null
          fee_notes?: string | null
          grades_offered?: string[]
          has_nursery?: boolean
          id?: string
          inspection_report_updated_at?: string | null
          inspection_report_url?: string | null
          is_active?: boolean
          kep_participant?: boolean
          language_primary?: string | null
          language_secondary?: string | null
          last_profile_scraped_at?: string | null
          last_verified_at?: string | null
          latitude?: number | null
          logo_url?: string | null
          longitude?: number | null
          master_data_notes?: string | null
          name_en?: string | null
          name_tc: string
          official_notice_updated_at?: string | null
          official_notice_url?: string | null
          official_profile_url?: string | null
          open_day_details?: string | null
          open_day_url?: string | null
          other_fees_note?: string | null
          phone?: string | null
          registration_fee_hkd?: number | null
          school_code?: string | null
          school_type: string
          schooland_facilities_summary?: string | null
          schooland_founded_year?: number | null
          schooland_free_scheme?: boolean | null
          schooland_group_tag?: string | null
          schooland_intro?: string | null
          schooland_nursery_service?: string | null
          schooland_operator_name?: string | null
          schooland_secondary_flags?: Json
          schooland_session_label?: string | null
          schooland_size_label?: string | null
          schooland_source_fields?: Json
          schooland_source_updated_at?: string | null
          schooland_source_url?: string | null
          schooland_staff_count?: number | null
          schooland_teacher_student_ratio?: string | null
          schooland_teaching_summary?: string | null
          schooland_url?: string | null
          session_type?: string | null
          updated_at?: string
          website?: string | null
        }
        Update: {
          address_en?: string | null
          address_tc?: string | null
          application_details?: string | null
          application_fee_hkd?: number | null
          application_status?: string | null
          application_url?: string | null
          created_at?: string
          data_source?: string
          district?: string
          email?: string | null
          fax?: string | null
          fee_annual_hkd?: number | null
          fee_certificate_updated_at?: string | null
          fee_certificate_url?: string | null
          fee_monthly_hkd?: number | null
          fee_notes?: string | null
          grades_offered?: string[]
          has_nursery?: boolean
          id?: string
          inspection_report_updated_at?: string | null
          inspection_report_url?: string | null
          is_active?: boolean
          kep_participant?: boolean
          language_primary?: string | null
          language_secondary?: string | null
          last_profile_scraped_at?: string | null
          last_verified_at?: string | null
          latitude?: number | null
          logo_url?: string | null
          longitude?: number | null
          master_data_notes?: string | null
          name_en?: string | null
          name_tc?: string
          official_notice_updated_at?: string | null
          official_notice_url?: string | null
          official_profile_url?: string | null
          open_day_details?: string | null
          open_day_url?: string | null
          other_fees_note?: string | null
          phone?: string | null
          registration_fee_hkd?: number | null
          school_code?: string | null
          school_type?: string
          schooland_facilities_summary?: string | null
          schooland_founded_year?: number | null
          schooland_free_scheme?: boolean | null
          schooland_group_tag?: string | null
          schooland_intro?: string | null
          schooland_nursery_service?: string | null
          schooland_operator_name?: string | null
          schooland_secondary_flags?: Json
          schooland_session_label?: string | null
          schooland_size_label?: string | null
          schooland_source_fields?: Json
          schooland_source_updated_at?: string | null
          schooland_source_url?: string | null
          schooland_staff_count?: number | null
          schooland_teacher_student_ratio?: string | null
          schooland_teaching_summary?: string | null
          schooland_url?: string | null
          session_type?: string | null
          updated_at?: string
          website?: string | null
        }
        Relationships: []
      }
      social_intel: {
        Row: {
          branch_identified: boolean | null
          competition_signals: Json | null
          content_type: string
          created_at: string | null
          engagement_score: number | null
          id: string
          match_confidence: string
          negative_keywords: string[] | null
          positive_keywords: string[] | null
          school_code: string
          school_id: string
          sentiment: string | null
          source_date: string | null
          source_type: string
          source_url: string
          structured_data: Json
        }
        Insert: {
          branch_identified?: boolean | null
          competition_signals?: Json | null
          content_type: string
          created_at?: string | null
          engagement_score?: number | null
          id?: string
          match_confidence: string
          negative_keywords?: string[] | null
          positive_keywords?: string[] | null
          school_code: string
          school_id: string
          sentiment?: string | null
          source_date?: string | null
          source_type: string
          source_url: string
          structured_data?: Json
        }
        Update: {
          branch_identified?: boolean | null
          competition_signals?: Json | null
          content_type?: string
          created_at?: string | null
          engagement_score?: number | null
          id?: string
          match_confidence?: string
          negative_keywords?: string[] | null
          positive_keywords?: string[] | null
          school_code?: string
          school_id?: string
          sentiment?: string | null
          source_date?: string | null
          source_type?: string
          source_url?: string
          structured_data?: Json
        }
        Relationships: [
          {
            foreignKeyName: "social_intel_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      social_posts_raw: {
        Row: {
          author_hash: string | null
          content_hash: string | null
          external_id: string
          fetched_at: string
          id: string
          platform: string
          posted_at: string | null
          raw_metadata: Json | null
          raw_text: string | null
          school_matches: Json | null
          sentiment: string | null
          topics: Json | null
          url: string | null
        }
        Insert: {
          author_hash?: string | null
          content_hash?: string | null
          external_id: string
          fetched_at?: string
          id?: string
          platform: string
          posted_at?: string | null
          raw_metadata?: Json | null
          raw_text?: string | null
          school_matches?: Json | null
          sentiment?: string | null
          topics?: Json | null
          url?: string | null
        }
        Update: {
          author_hash?: string | null
          content_hash?: string | null
          external_id?: string
          fetched_at?: string
          id?: string
          platform?: string
          posted_at?: string | null
          raw_metadata?: Json | null
          raw_text?: string | null
          school_matches?: Json | null
          sentiment?: string | null
          topics?: Json | null
          url?: string | null
        }
        Relationships: []
      }
      social_summary: {
        Row: {
          avg_interview_duration: number | null
          competition_level: string | null
          created_at: string | null
          data_year_range: string | null
          fee_estimates: Json | null
          heat_rank_district: number | null
          heat_rank_overall: number | null
          id: string
          interview_contributor_count: number | null
          interview_format_distribution: Json | null
          interview_posts: number | null
          last_updated: string | null
          negative_keywords: Json | null
          parent_interview_pct: number | null
          positive_keywords: Json | null
          school_code: string
          school_id: string
          sentiment_distribution: Json | null
          timeline_summary: Json | null
          top_interview_keywords: Json | null
          total_engagement: number | null
          total_posts: number | null
        }
        Insert: {
          avg_interview_duration?: number | null
          competition_level?: string | null
          created_at?: string | null
          data_year_range?: string | null
          fee_estimates?: Json | null
          heat_rank_district?: number | null
          heat_rank_overall?: number | null
          id?: string
          interview_contributor_count?: number | null
          interview_format_distribution?: Json | null
          interview_posts?: number | null
          last_updated?: string | null
          negative_keywords?: Json | null
          parent_interview_pct?: number | null
          positive_keywords?: Json | null
          school_code: string
          school_id: string
          sentiment_distribution?: Json | null
          timeline_summary?: Json | null
          top_interview_keywords?: Json | null
          total_engagement?: number | null
          total_posts?: number | null
        }
        Update: {
          avg_interview_duration?: number | null
          competition_level?: string | null
          created_at?: string | null
          data_year_range?: string | null
          fee_estimates?: Json | null
          heat_rank_district?: number | null
          heat_rank_overall?: number | null
          id?: string
          interview_contributor_count?: number | null
          interview_format_distribution?: Json | null
          interview_posts?: number | null
          last_updated?: string | null
          negative_keywords?: Json | null
          parent_interview_pct?: number | null
          positive_keywords?: Json | null
          school_code?: string
          school_id?: string
          sentiment_distribution?: Json | null
          timeline_summary?: Json | null
          top_interview_keywords?: Json | null
          total_engagement?: number | null
          total_posts?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "social_summary_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          child_birth_year: number | null
          created_at: string
          display_name: string | null
          email: string
          id: string
          notification_email: string | null
          preferred_districts: string[]
          updated_at: string
        }
        Insert: {
          child_birth_year?: number | null
          created_at?: string
          display_name?: string | null
          email: string
          id: string
          notification_email?: string | null
          preferred_districts?: string[]
          updated_at?: string
        }
        Update: {
          child_birth_year?: number | null
          created_at?: string
          display_name?: string | null
          email?: string
          id?: string
          notification_email?: string | null
          preferred_districts?: string[]
          updated_at?: string
        }
        Relationships: []
      }
      vacancies: {
        Row: {
          academic_year: string
          application_deadline: string | null
          created_at: string
          edb_published_date: string | null
          edb_source_url: string | null
          id: string
          is_current: boolean
          k1_vacancy: string
          k2_vacancy: string
          k3_vacancy: string
          n_vacancy: string
          school_id: string
          updated_at: string
        }
        Insert: {
          academic_year: string
          application_deadline?: string | null
          created_at?: string
          edb_published_date?: string | null
          edb_source_url?: string | null
          id?: string
          is_current?: boolean
          k1_vacancy?: string
          k2_vacancy?: string
          k3_vacancy?: string
          n_vacancy?: string
          school_id: string
          updated_at?: string
        }
        Update: {
          academic_year?: string
          application_deadline?: string | null
          created_at?: string
          edb_published_date?: string | null
          edb_source_url?: string | null
          id?: string
          is_current?: boolean
          k1_vacancy?: string
          k2_vacancy?: string
          k3_vacancy?: string
          n_vacancy?: string
          school_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vacancies_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      decrement_helpful_count: {
        Args: { p_intel_id: string }
        Returns: undefined
      }
      increment_helpful_count: {
        Args: { p_intel_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
