#!/usr/bin/env node
// Regenerate the logo manifest after public/logos has been cleaned:
//   - src/lib/schools/schoolLogoSources.ts  (LOCAL_SCHOOL_LOGO_FILES whitelist)
//   - supabase/seed/003_school_logos.sql    (logo_url mapping)
// Run: node scripts/regen_logo_manifest.mjs

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const LOGOS_DIR = path.join(ROOT, "public", "logos");
const TS_PATH = path.join(ROOT, "src", "lib", "schools", "schoolLogoSources.ts");
const SQL_PATH = path.join(ROOT, "supabase", "seed", "003_school_logos.sql");

const files = fs
  .readdirSync(LOGOS_DIR)
  .filter((f) => /^\d{6}\.(png|svg|webp)$/.test(f))
  .sort();

// --- schoolLogoSources.ts ---
const ts = `// Generated from public/logos by scripts/regen_logo_manifest.mjs.
// Only existing local logo files are listed here.

const LOCAL_SCHOOL_LOGO_FILES = new Set([
${files.map((f) => `  "${f}",`).join("\n")}
]);

export function hasLocalSchoolLogoFile(fileName: string): boolean {
  return LOCAL_SCHOOL_LOGO_FILES.has(fileName);
}
`;
fs.writeFileSync(TS_PATH, ts);

// --- 003_school_logos.sql ---
// One logo_url per school_code; prefer .png, then .svg, then .webp.
const EXT_RANK = { png: 0, svg: 1, webp: 2 };
const byCode = new Map();
for (const f of files) {
  const [code, ext] = f.split(".");
  const cur = byCode.get(code);
  if (!cur || EXT_RANK[ext] < EXT_RANK[cur.ext]) byCode.set(code, { ext, file: f });
}
const codes = [...byCode.entries()].sort(([a], [b]) => a.localeCompare(b));
const sql = [
  "-- School logo_url mapping. Generated by scripts/regen_logo_manifest.mjs.",
  "-- Reflects the cleaned public/logos asset set (placeholder & junk images removed).",
  "UPDATE schools SET logo_url = NULL WHERE logo_url IS NOT NULL;",
  ...codes.map(
    ([code, { file }]) =>
      `UPDATE schools SET logo_url = '/logos/${file}' WHERE school_code = '${code}';`
  ),
];
fs.writeFileSync(SQL_PATH, sql.join("\n") + "\n");

console.log(`logo files: ${files.length}`);
console.log(`unique school codes: ${byCode.size}`);
console.log(`wrote ${path.relative(ROOT, TS_PATH)}`);
console.log(`wrote ${path.relative(ROOT, SQL_PATH)}`);
